//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.3
//     from Assets/Scripts/Units/Player/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""GameMap"",
            ""id"": ""4069e178-02cf-4e9e-98b2-7a549efec4f8"",
            ""actions"": [
                {
                    ""name"": ""MovementPlayer1"",
                    ""type"": ""Value"",
                    ""id"": ""747810cd-3e4e-4593-9872-f3d2fd128fc1"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MovementPlayer2"",
                    ""type"": ""Value"",
                    ""id"": ""51d31bb3-c576-4fa1-a32c-ab1733f3695e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ResetBall"",
                    ""type"": ""Button"",
                    ""id"": ""066dde0e-278a-4e5a-b930-a39f135982d7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""0add3a22-3e78-47ea-949f-78cc749d8472"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""7a570179-6d5c-4622-923d-3da0f4ea8b61"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementPlayer1"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""4cf58ff6-06c7-46f6-9913-3f03e304d595"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementPlayer1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""63131748-0a29-4477-8445-ac7e05e8cd8a"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementPlayer1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""42198e2c-d342-4c6c-89d2-d471b308c043"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementPlayer1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""8f6b4b30-153e-4313-8c6a-7b1a18930230"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementPlayer1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""32e3b855-dff5-4e06-8ffc-94eb1a244917"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementPlayer2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""49bc20ad-6c6f-492d-93ec-716f143547ea"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementPlayer2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d301824f-38d8-470b-b0a6-dc1502fb73f5"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementPlayer2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""cfc31c57-e9d7-4ebf-8c2b-d81b589615fe"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementPlayer2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""51fe4185-876c-42bb-a873-b65157d4d5a0"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementPlayer2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""423192bc-a423-4246-aa48-4e67238bcf85"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": ""Hold(duration=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ResetBall"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e1d92a0e-5b4b-4391-a1c2-bf8b026dc80a"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GameMap
        m_GameMap = asset.FindActionMap("GameMap", throwIfNotFound: true);
        m_GameMap_MovementPlayer1 = m_GameMap.FindAction("MovementPlayer1", throwIfNotFound: true);
        m_GameMap_MovementPlayer2 = m_GameMap.FindAction("MovementPlayer2", throwIfNotFound: true);
        m_GameMap_ResetBall = m_GameMap.FindAction("ResetBall", throwIfNotFound: true);
        m_GameMap_Shoot = m_GameMap.FindAction("Shoot", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GameMap
    private readonly InputActionMap m_GameMap;
    private IGameMapActions m_GameMapActionsCallbackInterface;
    private readonly InputAction m_GameMap_MovementPlayer1;
    private readonly InputAction m_GameMap_MovementPlayer2;
    private readonly InputAction m_GameMap_ResetBall;
    private readonly InputAction m_GameMap_Shoot;
    public struct GameMapActions
    {
        private @PlayerControls m_Wrapper;
        public GameMapActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @MovementPlayer1 => m_Wrapper.m_GameMap_MovementPlayer1;
        public InputAction @MovementPlayer2 => m_Wrapper.m_GameMap_MovementPlayer2;
        public InputAction @ResetBall => m_Wrapper.m_GameMap_ResetBall;
        public InputAction @Shoot => m_Wrapper.m_GameMap_Shoot;
        public InputActionMap Get() { return m_Wrapper.m_GameMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameMapActions set) { return set.Get(); }
        public void SetCallbacks(IGameMapActions instance)
        {
            if (m_Wrapper.m_GameMapActionsCallbackInterface != null)
            {
                @MovementPlayer1.started -= m_Wrapper.m_GameMapActionsCallbackInterface.OnMovementPlayer1;
                @MovementPlayer1.performed -= m_Wrapper.m_GameMapActionsCallbackInterface.OnMovementPlayer1;
                @MovementPlayer1.canceled -= m_Wrapper.m_GameMapActionsCallbackInterface.OnMovementPlayer1;
                @MovementPlayer2.started -= m_Wrapper.m_GameMapActionsCallbackInterface.OnMovementPlayer2;
                @MovementPlayer2.performed -= m_Wrapper.m_GameMapActionsCallbackInterface.OnMovementPlayer2;
                @MovementPlayer2.canceled -= m_Wrapper.m_GameMapActionsCallbackInterface.OnMovementPlayer2;
                @ResetBall.started -= m_Wrapper.m_GameMapActionsCallbackInterface.OnResetBall;
                @ResetBall.performed -= m_Wrapper.m_GameMapActionsCallbackInterface.OnResetBall;
                @ResetBall.canceled -= m_Wrapper.m_GameMapActionsCallbackInterface.OnResetBall;
                @Shoot.started -= m_Wrapper.m_GameMapActionsCallbackInterface.OnShoot;
                @Shoot.performed -= m_Wrapper.m_GameMapActionsCallbackInterface.OnShoot;
                @Shoot.canceled -= m_Wrapper.m_GameMapActionsCallbackInterface.OnShoot;
            }
            m_Wrapper.m_GameMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MovementPlayer1.started += instance.OnMovementPlayer1;
                @MovementPlayer1.performed += instance.OnMovementPlayer1;
                @MovementPlayer1.canceled += instance.OnMovementPlayer1;
                @MovementPlayer2.started += instance.OnMovementPlayer2;
                @MovementPlayer2.performed += instance.OnMovementPlayer2;
                @MovementPlayer2.canceled += instance.OnMovementPlayer2;
                @ResetBall.started += instance.OnResetBall;
                @ResetBall.performed += instance.OnResetBall;
                @ResetBall.canceled += instance.OnResetBall;
                @Shoot.started += instance.OnShoot;
                @Shoot.performed += instance.OnShoot;
                @Shoot.canceled += instance.OnShoot;
            }
        }
    }
    public GameMapActions @GameMap => new GameMapActions(this);
    public interface IGameMapActions
    {
        void OnMovementPlayer1(InputAction.CallbackContext context);
        void OnMovementPlayer2(InputAction.CallbackContext context);
        void OnResetBall(InputAction.CallbackContext context);
        void OnShoot(InputAction.CallbackContext context);
    }
}
